// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // The CLI (migrate/introspect/studio) always talks to the database directly, never through
  // Supabase's PgBouncer pool — pooled connections don't support the DDL/prepared statements
  // migrations need. The Next.js app itself connects via a driver adapter using DATABASE_URL
  // (pooled) instead — see src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
